version: '3'

services:
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 15432:5432